# -*- coding: utf-8 -*-
"""CSVFile_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srYkPy0I99GJDd3ctjOZ1J7GH-1PD8xI
"""

import csv
import random
from datetime import datetime, timedelta

TOTAL_RECORDS = 500
ATM_LOCATIONS = ['Mumbai', 'Delhi', 'Bangalore', 'Chennai', 'Kolkata']
DEVICE_IDS = [f'atm_{i:03d}' for i in range(1, 21)]

CUSTOMER_IDS = [f'cust_{i:04d}' for i in range(1000, 1021)]
CUSTOMER_KNOWN_LOCATIONS = {
    "cust_1001": ["Delhi"],
    "cust_1002": ["Mumbai", "Bangalore"],
    "cust_1003": ["Chennai"],
}

FRAUD_PROBABILITY = 0.35
FRAUD_REASONS = ["High amount", "Location mismatch", "Multiple transactions in short interval"]

def generate_random_timestamp():
    start_date = datetime.utcnow() - timedelta(days=5)
    random_seconds = random.randint(0, 5 * 24 * 60 * 60)
    return (start_date + timedelta(seconds=random_seconds)).isoformat()

with open('atm_transactions.csv', mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=[
        'transaction_id', 'customer_id', 'timestamp', 'amount', 'device_id', 'atm_location', 'fraud_reason'
    ])
    writer.writeheader()

    for _ in range(TOTAL_RECORDS):
        customer_id = random.choice(CUSTOMER_IDS)
        known_locations = CUSTOMER_KNOWN_LOCATIONS.get(customer_id, ATM_LOCATIONS)

        # Amount random between 500–9500 normally
        amount = round(random.randint(500, 9500) + random.randint(0, 99)/100, 2)
        atm_location = random.choice(ATM_LOCATIONS)

        fraud_reason = ""
        if random.random() <= FRAUD_PROBABILITY:
            reason_type = random.choice(FRAUD_REASONS)
            fraud_reason = reason_type
            if reason_type == "High amount":
                amount = round(random.randint(20001, 30000) + random.randint(0, 99)/100, 2)
            elif reason_type == "Location mismatch":
                wrong_locations = [loc for loc in ATM_LOCATIONS if loc not in known_locations]
                if wrong_locations:
                    atm_location = random.choice(wrong_locations)
            elif reason_type == "Multiple transactions in short interval":
                # Just mark the reason; no extra logic needed in CSV
                pass

        transaction = {
            'transaction_id': f"txn_{random.randint(100000, 999999)}",
            'customer_id': customer_id,
            'timestamp': generate_random_timestamp(),
            'amount': amount,
            'device_id': random.choice(DEVICE_IDS),
            'atm_location': atm_location,
            'fraud_reason': fraud_reason
        }

        writer.writerow(transaction)

print("CSV file 'atm_transactions.csv' generated with 500 records.")